### ISSUE TITLE
Production certificate not work

### ISSUE THREAD

**Issue by isaadansari** [ljsystem/bankid#12]
Hi,
I have used this code and created some custom form, where I am validating the bankid using your code.
It is working fine on local environment using your certificates, however I am having problems with the production certificates.

I have initialied the object as following:

```
 $bankId = new \LJSystem\BankID\BankID(
        'prod',
        __DIR__ . '/certs/prod.pem',
        __DIR__ . '/certs/prod_cacert.cer',
        __DIR__ . '/certs/prod.key',
        'Keyphase2222'
    );
``` 
The paths are correct, dont worry. the problem is you are using, the .cer and .pem while I only got the .cer from my bank.
I was able to generate the .pem with openssl command using prod.key and .cer but that is not working.

Can you guide me in the correct direction.

Regards

**Comment by perifer** [comment]
Certs are tricky. I tried to document it in the readme, partly for my own need because I always forget how to do it. So look at that if you haven’t. There is also an issue in here I think which could cover some things. Good luck!

**Comment by isaadansari** [comment]
Hi @perifer 
I am facing this issue, can you pls help me there. Do I need to update the certificate sent by the bank on the website too, in my case I have a cloudflare certifacte so I might have to update it. 

`cURL error 60: SSL certificate problem: unable to get local issuer certificate`

Thanks

**Comment by perifer** [comment]
No exactly sure what the workflow is here but I can at least say for certain that the only place you will be using the BankID-certificate is when you communicate with the bankid-api. The best info I can give you is probably the info at https://github.com/ljsystem/bankid#certificates.

For exampe, it says that you need a .cer and a .key - so if you only got a .cer you are probably missing one piece. 

I will close this issue since giving support on how to handle certificates is not really something I'm confident doing at the moment. Thank you for understanding!
